version: "3.7"

      
services:
  postgres:
    container_name: container_postgres
    image: 
      postgres:14.5
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=1GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=1GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_trgm"
      - "-c"
      - "pg_trgm.set_limit=0.3"
      - "-c"
      - "pg_trgm.similarity_threshold=0.3"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
      # - ../2. Init Database:/docker-entrypoint-initdb.d
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 0.5G
    # restart:
      # unless-stopped

  
  nginx:
    container_name:
      container_nginx
    build:
      ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/sites-enabled/:/etc/nginx/sites-enabled/
      - ./logs/nginx/:/var/log/nginx/
      - ./first-film/app/static:/var/www/html/first-film/static
      - ./first-film/app/admin/static:/var/www/html/first-film/admin/static
      - /etc/letsencrypt:/var/www/html/first-film/ssl
    depends_on:
      - postgres
      - first-film    
    # restart: 
      # unless-stopped
      

  first-film:
    container_name:
      container_first-film
    volumes:
      - ./first-film/:/src/
      - ./logs/first-film/:/var/log/uwsgi
    build:
      ./first-film
    environment:
      POSTGRES_IP: ${POSTGRES_IP}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      ADMIN_1: ${ADMIN_1}
      ADMIN_1_PASS: ${ADMIN_1_PASS}
      ADMIN_2: ${ADMIN_2}
      ADMIN_2_PASS: ${ADMIN_2_PASS}
      
      APP_SECRET_KEY: ${APP_SECRET_KEY}
    ports:
      - 7000:7000
      - 7001:7001
    depends_on:
      - postgres    
    # restart:
      # unless-stopped
